package xywx.dao;

import java.util.Date;

public class Attachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.id
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.type
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.location
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.detail
     *
     * @mbggenerated Tue Apr 26 21:13:32 CST 2016
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.effect
     *
     * @mbggenerated Tue Apr 26 21:13:32 CST 2016
     */
    private String effect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.id
     *
     * @return the value of attachment.id
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.id
     *
     * @param id the value for attachment.id
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.type
     *
     * @return the value of attachment.type
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.type
     *
     * @param type the value for attachment.type
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.location
     *
     * @return the value of attachment.location
     *
     * @mbggenerated Tue Apr 26 21:13:31 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.location
     *
     * @param location the value for attachment.location
     *
     * @mbggenerated Tue Apr 26 21:13:32 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.detail
     *
     * @return the value of attachment.detail
     *
     * @mbggenerated Tue Apr 26 21:13:32 CST 2016
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.detail
     *
     * @param detail the value for attachment.detail
     *
     * @mbggenerated Tue Apr 26 21:13:32 CST 2016
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.effect
     *
     * @return the value of attachment.effect
     *
     * @mbggenerated Tue Apr 26 21:13:32 CST 2016
     */
    public String getEffect() {
        return effect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.effect
     *
     * @param effect the value for attachment.effect
     *
     * @mbggenerated Tue Apr 26 21:13:32 CST 2016
     */
    public void setEffect(String effect) {
        this.effect = effect == null ? null : effect.trim();
    }
    
    private String localName;

	public String getLocalName() {
		return localName;
	}

	public void setLocalName(String localName) {
		this.localName = localName;
	}
	
	public Date optime;

	public Date getOptime() {
		return optime;
	}

	public void setOptime(Date optime) {
		this.optime = optime;
	}
}