package xywx.dao;

import java.util.Date;

public class Coach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.id
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.name
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.describe
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.detailLink
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    private String detaillink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.id
     *
     * @return the value of coach.id
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.id
     *
     * @param id the value for coach.id
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.name
     *
     * @return the value of coach.name
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.name
     *
     * @param name the value for coach.name
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.describe
     *
     * @return the value of coach.describe
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.describe
     *
     * @param describe the value for coach.describe
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.detailLink
     *
     * @return the value of coach.detailLink
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public String getDetaillink() {
        return detaillink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.detailLink
     *
     * @param detaillink the value for coach.detailLink
     *
     * @mbggenerated Tue Apr 26 21:05:15 CST 2016
     */
    public void setDetaillink(String detaillink) {
        this.detaillink = detaillink == null ? null : detaillink.trim();
    }
    
    private String state;

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
	
	private Date optime;

	public Date getOptime() {
		return optime;
	}

	public void setOptime(Date optime) {
		this.optime = optime;
	}

	
}