package xywx.dao;

import java.sql.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.origin
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.name
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.openid
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.gender
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.age
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.career
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private String career;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.place
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    private String place;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.origin
     *
     * @return the value of customer.origin
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.origin
     *
     * @param origin the value for customer.origin
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.name
     *
     * @return the value of customer.name
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.name
     *
     * @param name the value for customer.name
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.openid
     *
     * @return the value of customer.openid
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.openid
     *
     * @param openid the value for customer.openid
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.gender
     *
     * @return the value of customer.gender
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.gender
     *
     * @param gender the value for customer.gender
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.age
     *
     * @return the value of customer.age
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.age
     *
     * @param age the value for customer.age
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.career
     *
     * @return the value of customer.career
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.career
     *
     * @param career the value for customer.career
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setCareer(String career) {
        this.career = career == null ? null : career.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.place
     *
     * @return the value of customer.place
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.place
     *
     * @param place the value for customer.place
     *
     * @mbggenerated Tue Apr 26 21:15:45 CST 2016
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }
    
    private String testcount;

	public String getTestcount() {
		return testcount;
	}

	public void setTestcount(String testcount) {
		this.testcount = testcount;
	}
	
	private Date createtime;

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
}