package xywx.dao;

public class Name {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name.id
     *
     * @mbggenerated Tue Apr 26 11:52:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column name.name
     *
     * @mbggenerated Tue Apr 26 11:52:06 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name.id
     *
     * @return the value of name.id
     *
     * @mbggenerated Tue Apr 26 11:52:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name.id
     *
     * @param id the value for name.id
     *
     * @mbggenerated Tue Apr 26 11:52:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column name.name
     *
     * @return the value of name.name
     *
     * @mbggenerated Tue Apr 26 11:52:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column name.name
     *
     * @param name the value for name.name
     *
     * @mbggenerated Tue Apr 26 11:52:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}