package xywx.dao;

public class Testdetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdetails.id
     *
     * @mbggenerated Tue Apr 26 21:19:36 CST 2016
     */
    private Integer id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdetails.score
     *
     * @mbggenerated Tue Apr 26 21:19:36 CST 2016
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdetails.id
     *
     * @return the value of testdetails.id
     *
     * @mbggenerated Tue Apr 26 21:19:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdetails.id
     *
     * @param id the value for testdetails.id
     *
     * @mbggenerated Tue Apr 26 21:19:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdetails.score
     *
     * @return the value of testdetails.score
     *
     * @mbggenerated Tue Apr 26 21:19:36 CST 2016
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdetails.score
     *
     * @param score the value for testdetails.score
     *
     * @mbggenerated Tue Apr 26 21:19:36 CST 2016
     */
    public void setScore(Integer score) {
        this.score = score;
    }
    
    private Integer testid;
    private Integer questionid;
    private String questionname;

	public String getQuestionname() {
		return questionname;
	}

	public void setQuestionname(String questionname) {
		this.questionname = questionname;
	}

	public Integer getTestid() {
		return testid;
	}

	public void setTestid(Integer testid) {
		this.testid = testid;
	}

	public Integer getQuestionid() {
		return questionid;
	}

	public void setQuestionid(Integer questionid) {
		this.questionid = questionid;
	}
}