package xywx.dao;

import java.util.Date;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.testtime
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    private Date testtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.energy
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    private Integer energy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.customerid
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    private Integer customerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.testtime
     *
     * @return the value of test.testtime
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public Date getTesttime() {
        return testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.testtime
     *
     * @param testtime the value for test.testtime
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public void setTesttime(Date testtime) {
        this.testtime = testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.energy
     *
     * @return the value of test.energy
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public Integer getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.energy
     *
     * @param energy the value for test.energy
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public void setEnergy(Integer energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.customerid
     *
     * @return the value of test.customerid
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.customerid
     *
     * @param customerid the value for test.customerid
     *
     * @mbggenerated Wed Apr 27 21:46:40 CST 2016
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }
    
    
}