package xywx.dao;

public class Topicoption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicoption.id
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicoption.qid
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    private Integer qid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicoption.showMean
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    private String showmean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicoption.optionValue
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    private Integer optionvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicoption.id
     *
     * @return the value of topicoption.id
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicoption.id
     *
     * @param id the value for topicoption.id
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicoption.qid
     *
     * @return the value of topicoption.qid
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicoption.qid
     *
     * @param qid the value for topicoption.qid
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicoption.showMean
     *
     * @return the value of topicoption.showMean
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public String getShowmean() {
        return showmean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicoption.showMean
     *
     * @param showmean the value for topicoption.showMean
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public void setShowmean(String showmean) {
        this.showmean = showmean == null ? null : showmean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicoption.optionValue
     *
     * @return the value of topicoption.optionValue
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public Integer getOptionvalue() {
        return optionvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicoption.optionValue
     *
     * @param optionvalue the value for topicoption.optionValue
     *
     * @mbggenerated Tue Apr 26 21:22:11 CST 2016
     */
    public void setOptionvalue(Integer optionvalue) {
        this.optionvalue = optionvalue;
    }
}